name: Security News Automation

on:
  schedule:
    - cron: "0 0 * * *"   # 매일 00:00 UTC 실행 (한국 09:00)
    #- cron: "*/5 * * * *"   # 매 5분마다 실행
  workflow_dispatch:

jobs:
  crawl-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: |
          echo "GEMINI_API_KEY: ${GEMINI_API_KEY}"
          node mcp-server.js
        env:
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}